In [3]:
from gerrychain import Graph

ny_graph = Graph.from_file("./NY/NY.shp")
print("Graph loaded")

/Users/rishab/Library/Python/3.9/lib/python/site-packages/gerrychain/graph/graph.py:274: UserWarning: Found islands (degree-0 nodes). Indices of islands: {10308}
  warnings.warn(
/Users/rishab/Library/Python/3.9/lib/python/site-packages/gerrychain/graph/graph.py:179: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  areas = df.geometry.area.to_dict()


Graph loaded


In [8]:
print(
    (ny_graph.adj)
)

{0: {27: {'shared_perim': 0.0357298603808912}, 25: {'shared_perim': 0.03365134711696591}, 24: {'shared_perim': 0.01139568646166476}, 30: {'shared_perim': 0.027560826197311632}, 32: {'shared_perim': 0.012459643164666575}}, 1: {27: {'shared_perim': 0.02333932510186579}, 3097: {'shared_perim': 0.044602620847221094}, 5239: {'shared_perim': 0.14536513405494533}, 5226: {'shared_perim': 0.01492045131500725}, 20: {'shared_perim': 0.11221416482954309}, 11: {'shared_perim': 0.09949832371544003}, 12: {'shared_perim': 0.22409468777754848}, 26: {'shared_perim': 0.053817307528254026}, 5265: {'shared_perim': 0.007418470592439759}, 3099: {'shared_perim': 0.02729864187758828}, 5240: {'shared_perim': 0.053299704991404}, 19: {'shared_perim': 0.009328447187552123}}, 2: {36: {'shared_perim': 0.06862655690122332}, 5: {'shared_perim': 0.030958810351234944}, 34: {'shared_perim': 0.03010444649783401}, 31: {'shared_perim': 0.08142443234586377}, 14: {'shared_perim': 0.014450008688467159}}, 3: {8779: {'shared_per

In [15]:
import numpy as np

t = np.load("./data/states/NY_dists26_HVAPopt_4.5%_5000_sbl50_score0_8.npy")

print(t)


[[2. 2. 2. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [3. 3. 3. ... 1. 1. 1.]
 [3. 3. 3. ... 1. 1. 1.]
 [3. 3. 3. ... 2. 2. 2.]]
