In [16]:
# from gerrychain import Graph

# ny_graph = Graph.from_file("./NY/NY.shp")
# print("Graph loaded")

/Users/rishab/Library/Python/3.9/lib/python/site-packages/gerrychain/graph/graph.py:274: UserWarning: Found islands (degree-0 nodes). Indices of islands: {10308}
  warnings.warn(
/Users/rishab/Library/Python/3.9/lib/python/site-packages/gerrychain/graph/graph.py:179: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  areas = df.geometry.area.to_dict()


Graph loaded


In [26]:
# print(
#     (ny_graph.columns)
# )

AttributeError: 'Graph' object has no attribute 'columns'

In [43]:
import numpy as np

# StateAnalysis
Three_NY = np.load("./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy")
Five_NY = np.load("./data/states/0.5_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy")
Seven_NY = np.load("./data/states/0.7_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy")
Nine_NY = np.load("./data/states/0.7_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy")

print(Seven_NY)


[[26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.
  26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.
  26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.]
 [26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.
  26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.
  26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26. 26.]]


In [23]:
# S

import numpy as np

t = np.load("./data/states/NY_dists26_HVAPopt_4.5%_5000_sbl50_score0_0.npy")

print(t)


[[2. 2. 2. ... 1. 1. 1.]
 [2. 2. 2. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [3. 3. 3. ... 2. 2. 2.]
 [3. 2. 2. ... 2. 2. 2.]
 [3. 2. 2. ... 3. 3. 3.]]


In [ ]:
[0.1, 0.5, 0.7]
[18, 2, 0]