In [16]:
# from gerrychain import Graph

# ny_graph = Graph.from_file("./NY/NY.shp")
# print("Graph loaded")

/Users/rishab/Library/Python/3.9/lib/python/site-packages/gerrychain/graph/graph.py:274: UserWarning: Found islands (degree-0 nodes). Indices of islands: {10308}
  warnings.warn(
/Users/rishab/Library/Python/3.9/lib/python/site-packages/gerrychain/graph/graph.py:179: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  areas = df.geometry.area.to_dict()


Graph loaded


In [26]:
# print(
#     (ny_graph.columns)
# )

AttributeError: 'Graph' object has no attribute 'columns'

In [45]:
import numpy as np

# StateAnalysis
Three_NY = np.load("./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy")
Five_NY = np.load("./data/states/0.5_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy")
Seven_NY = np.load("./data/states/0.7_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy")
Nine_NY = np.load("./data/states/0.7_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy")

print(Five_NY)


[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
  2. 2. 2. 2. 2. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


In [23]:
# S

import numpy as np

t = np.load("./data/states/NY_dists26_HVAPopt_4.5%_5000_sbl50_score0_0.npy")

print(t)


[[2. 2. 2. ... 1. 1. 1.]
 [2. 2. 2. ... 1. 1. 1.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [3. 3. 3. ... 2. 2. 2.]
 [3. 2. 2. ... 2. 2. 2.]
 [3. 2. 2. ... 3. 3. 3.]]


In [39]:
## Recurse through ./data/states
## get filenames
## for every filename starting with 0.3, we get the number of steps
## create a dict with max steps

import os
import numpy as np

files = os.listdir("./data/states")

final_data = {}

for tolerance in [0.1, 0.3, 0.4, 0.5, 0.7]:

    max_steps = {}
    for file in files:
        if file.startswith(str(tolerance)) and file.endswith(".npy") and "HVAPopt" in file:
            steps = int(file.split("_")[5])

            if steps not in max_steps:
                max_steps[steps] = 0

            inp_districts = np.load("./data/states/" + file)

            print("./data/states/" + file, len(inp_districts))

            for i in range(len(inp_districts)):
                max_steps[steps] = max(max_steps[steps], max(inp_districts[i]))

    final_data[tolerance] = max_steps

./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_8.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_9.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_7.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_6.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_4.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_5.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_1.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_0.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_2.npy 2
./data/states/0.1_NY_dists26_HVAPopt_4.5%_100_sbl50_score0_3.npy 2
./data/states/0.3_NY_dists26_HVAPopt_4.5%_2000_sbl50_score0_2.npy 40
./data/states/0.3_NY_dists26_HVAPopt_4.5%_2000_sbl50_score0_3.npy 40
./data/states/0.3_NY_dists26_HVAPopt_4.5%_2000_sbl50_score0_1.npy 40
./data/states/0.3_NY_dists26_HVAPopt_4.5%_2000_sbl50_score0_0.npy 40
./data/states/0.3_NY_dists26_HVAPopt_4.5%_1000_sbl50_s

In [40]:
final_data

{0.1: {100: 18.0},
 0.3: {2000: 6.0, 1000: 6.0, 100: 4.0, 5000: 6.0},
 0.4: {100: 4.0},
 0.5: {100: 2.0},
 0.7: {100: 0}}

In [22]:
import pandas as pd

data = pd.read_pickle("./data/states/0.3_NY_dists26_HVAPopt_4.5%_5000_sbl50_score0_0_max_part.p")

In [24]:
data['HVAP']

{20: 20634,
 23: 31157,
 14: 145273,
 15: 120451,
 13: 233126,
 16: 49998,
 19: 51452,
 24: 22934,
 21: 23661,
 18: 28254,
 17: 36971,
 26: 112786,
 10: 88775,
 7: 102472,
 11: 254492,
 9: 277644,
 8: 68951,
 22: 74191,
 25: 83413,
 3: 126330,
 4: 203845,
 2: 243268,
 12: 240802,
 5: 102865,
 6: 102065,
 1: 80076}